This PR will update the readme to be up to date with the repo content
asreview/semantic-clusters pull request #19
Opened 2021-11-05 16:23 UTC by JTeijema

2021-11-09 14:52 UTC, JTeijema commented
See https://github.com/JTeijema/semantic-clusters/tree/readme-update for a easier review.

2021-11-10 07:39 UTC, Rensvandeschoot approved these changes

2021-11-10 07:39 UTC, Rensvandeschoot commented
Nice work! I have added some hyperlinks and contact information.

2021-11-10 08:23 UTC, J535D165 requested changes

2021-11-10 08:23 UTC, J535D165 commented on README.md
> +an [ASReview data object](https://asreview.readthedocs.io/en/latest/API/reference.html?highlight=data%20object#asreview-data), in order to cluster records based on semantic
```suggestion
an [ASReview data object](https://asreview.readthedocs.io/en/latest/API/reference.html#asreview-data), in order to cluster records based on semantic
```

2021-11-10 08:23 UTC, J535D165 commented on README.md
> +py asreviewcontrib\semantic_clustering\main.py -f <url or local file>
```suggestion
python asreviewcontrib\semantic_clustering\main.py -f <url or local file>
```

2021-11-10 08:23 UTC, J535D165 commented on README.md
> +py asreviewcontrib\semantic_clustering\main.py -f <url or local file>
Also for the others.

2021-11-10 08:23 UTC, J535D165 commented on README.md
> +dataset](https://asreview.readthedocs.io/en/latest/intro/datasets.html?highlight=ptsd#featured-datasets), and can be used as a functionality test.
```suggestion
dataset](https://asreview.readthedocs.io/en/latest/intro/datasets.html#featured-datasets), and can be used as a functionality test.
```

2021-11-10 12:34 UTC, Rensvandeschoot approved these changes

2021-11-11 09:00 UTC, Rensvandeschoot approved these changes

2021-11-11 09:00 UTC, merged