ASReview entrypoint
asreview/semantic-clusters pull request #24
Opened 2021-11-10 12:04 UTC by JTeijema

This PR will turn the semantic clustering into an ASReview entrypoint. It should also remove hardcoded file storage.

2021-11-12 15:44 UTC, JTeijema commented
Merge after #22 and #23 are merged! This PR creates the ASReview entrypoint.

![image](https://user-images.githubusercontent.com/28191416/141494132-aefb4c02-d346-4c51-b3b0-0834af97d811.png)

2021-11-12 15:47 UTC, JTeijema commented
Final PR will be the file storage implementation

2021-11-15 13:14 UTC, J535D165 commented
> Merge after #22 and #23 are merged! This PR creates the ASReview entrypoint.
> 
> ![image](https://user-images.githubusercontent.com/28191416/141494132-aefb4c02-d346-4c51-b3b0-0834af97d811.png)

This command doesn't return the help, but the error ;) Consider renaming the entry point.

2021-11-15 15:34 UTC, JTeijema commented
Renaming will be done all at once in a future PR

2021-11-15 15:41 UTC, JTeijema commented
Ready to merge!

2021-11-15 23:51 UTC, J535D165 requested changes
I don't feel like merging bugs/broken code into main is a good idea. I'm suggesting changes (and rename afterward).

2021-11-15 23:51 UTC, J535D165 commented on asreviewcontrib/semantic_clustering/main.py
> +    extension_name = "asreview-semantic-clustering"
```suggestion
    extension_name = "semantic_clustering"
```

2021-11-15 23:51 UTC, J535D165 commented on asreviewcontrib/semantic_clustering/main.py
> +    parser = argparse.ArgumentParser(prog='asreview semantic clustering')
```suggestion
    parser = argparse.ArgumentParser(prog='asreview semantic_clustering')
```

2021-11-15 23:51 UTC, J535D165 commented on setup.py
> +            "semantic-clustering = asreviewcontrib.semantic_clustering.main:SemClusEntryPoint",  # noqa: E501
```suggestion
            "semantic_clustering = asreviewcontrib.semantic_clustering.main:SemClusEntryPoint",  # noqa: E501
```

2021-11-16 08:28 UTC, J535D165 approved these changes

2021-11-16 08:29 UTC, merged

2021-11-16 08:29 UTC, J535D165 commented
Thanks!